version: "3.8"
services:
  db:
    image: mysql:5.7
    cap_drop:
       - NET_ADMIN
       - SYS_ADMIN
    environment:
      MYSQL_ROOT_PASSWORD: 195418
      MYSQL_DATABASE: market
      MYSQL_ROOT_HOST: '%'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p195418"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
        - ./sqlinit:/docker-entrypoint-initdb.d
  backend:
     build: ./backend
     container_name: flask_app
     volumes:
       - ./backend:/app
     ports:
       - "5000:5000"
     environment:
      FLASK_ENV: development
      URI_DB: mysql://root:195418@db:3306/market
      URI_DB_TESTING: mysql://root:195418@db:3306/market
     depends_on:
       - db
  frontend:
     build: ./frontend
     container_name: react_app
     ports:
       - "3000:80"
volumes:
  db_data:
  
