"""load db

Revision ID: 4192d94c4ce7
Revises: 
Create Date: 2025-03-11 19:35:30.227940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4192d94c4ce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MS_AUTHORS',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    op.create_table('MS_BOOKS',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('price', sa.String(length=320), nullable=False),
    sa.Column('author', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('title')
    )
    op.create_table('MS_SALES',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MS_SALES')
    op.drop_table('MS_BOOKS')
    op.drop_table('MS_AUTHORS')
    # ### end Alembic commands ###
