"""quit price of book

Revision ID: 1885e3780cc8
Revises: 4192d94c4ce7
Create Date: 2025-03-12 15:09:34.296121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1885e3780cc8'
down_revision = '4192d94c4ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MS_BOOKS', schema=None) as batch_op:
        batch_op.drop_index('price')
        batch_op.drop_column('price')

    with op.batch_alter_table('MS_SALES', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MS_SALES', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('MS_BOOKS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.VARCHAR(length=320), nullable=False))
        batch_op.create_index('price', ['price'], unique=True)

    # ### end Alembic commands ###
