"""test

Revision ID: c6d7f233c7f7
Revises: 1885e3780cc8
Create Date: 2025-03-12 15:19:46.189794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6d7f233c7f7'
down_revision = '1885e3780cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('MS_SALES', schema=None) as batch_op:
        batch_op.drop_index('_id')

    op.drop_table('MS_SALES')
    with op.batch_alter_table('MS_BOOKS', schema=None) as batch_op:
        batch_op.drop_index('_id')
        batch_op.drop_index('title')

    op.drop_table('MS_BOOKS')
    with op.batch_alter_table('MS_AUTHORS', schema=None) as batch_op:
        batch_op.drop_index('_id')

    op.drop_table('MS_AUTHORS')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MS_AUTHORS',
    sa.Column('_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('MS_AUTHORS', schema=None) as batch_op:
        batch_op.create_index('_id', ['_id'], unique=True)

    op.create_table('MS_BOOKS',
    sa.Column('_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('description', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('MS_BOOKS', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=True)
        batch_op.create_index('_id', ['_id'], unique=True)

    op.create_table('MS_SALES',
    sa.Column('_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('MS_SALES', schema=None) as batch_op:
        batch_op.create_index('_id', ['_id'], unique=True)

    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###
